gofannon/arxiv/__init__.py, gofannon/basic_math/__init__.py, gofannon/github/__init__.py, gofannon/reasoning/__init__.py, pyproject.toml, tests/test_arxiv.py, tests/test_basic_math.py, tests/test_github.py, tests/test_integrations.py, tests/test_reasoning.py
Removed Bulk Imports, now only expected functions are imported.
Will Need new Issue to update example to use more specific imports:
```
from gofannon.basic_math import Addition  
from gofannon.basic_math.addition import Addition  
```
#21
* Issue numbers (e.g., #123, #456)
* PR numbers (e.g., #789)
In a colab notebook:
```
from gofannon.config import FunctionRegistry
from gofannon.basic_math.addition import Addition  
from pprint import pprint  
pprint(FunctionRegistry.get_tools())  
```
yields:
```
[{'function': {'description': 'Calculate the sum of two numbers',
'name': 'addition',
'parameters': {'properties': {'num1': {'description': 'The '
'first '
'number',
'type': 'number'},
'num2': {'description': 'The '
'second '
'number',
'type': 'number'}},
'required': ['num1', 'num2'],
'type': …
```
=> Solves #21 - Only include specified tools

examples/Ollama_Example.ipynb
Adds a working Ollama Example. 
Closes #17 
Example runs in Colab on a T4
Adds one new file.
=> Add Ollama Example

ROADMAP.md, docs/headless_browser/headless_browser_get.md, docs/headless_browser/index.md, examples/Headless_Browser_GET.ipynb, gofannon/headless_browser/base.py, gofannon/headless_browser/headless_browser_get.py, pyproject.toml, tests/test_headless_browser.py
This PR introduces the headless browser base class, and a trivial initial function a GET (for a page that requires Java script rendering. )
Closes #19 
Closes #5 
Added tests and an example that load a webpage I made 5 years ago while learning material UI. It's a silly page, but it is good because 
1. I own it, and can control it / keep it static.
2. It's a very minimal page, in which Java Script won't render, or it does (ie there are no fall backs or other things modern pages do. See the test. 
-- Getting lazy from this point on for reasons - iykyk --
Include an example of how to use the …
=> Implement Headless Browser

docs/how_to_contribute.md
Add DCO Signoff to the how-to-contribute documentation 
Closes #13 
Not required
None
N/A
N/A
None
=> Add signoff info to the how-to-contribute docs

.github/workflows/unit-tests.yml, ROADMAP.md, docs/google_search/google_search.md, docs/google_search/index.md, examples/Google_Search.ipynb, gofannon/config.py, gofannon/google_search/google_search.py, pyproject.toml, tests/test_google_search.py
*   This PR adds a Google Search tool to the Gofannon repository.  
*   The tool allows LLMs to query the Google Search API and retrieve snippets of search results.  
*   This improves the existing repository by enabling LLMs to access up-to-date information.  
Closes #31 
* Unit tests added to ensure the tool returns results for valid queries and handles errors gracefully.  
* Working example notebook
* New files: `gofannon/google_search/__init__.py`, `gofannon/google_search/google_search.py`  
* Modified files: `gofannon/config.py`, `ROADMAP.md`  
* New tests: `tests/test_google_search.py` 
* New examples: `examples/Google_Search.ipynb`
```python  
from gofannon.google_search.google_search import GoogleSearch  
google_search = GoogleSearch(api_key="YOUR_API_KEY", …
```
=> Add Google Search Tool

.github/ISSUE_TEMPLATE/function_proposal.md
* What is the purpose of this PR?
* What new function or feature is being added?
* How does it improve the existing repository?
* Issue numbers (e.g., #123, #456)
* PR numbers (e.g., #789) …
=> [cowboy] - Drop code example in template

.github/workflows/build-site.yml
* What is the purpose of this PR?
* What new function or feature is being added?
* How does it improve the existing repository?
* Issue numbers (e.g., #123, #456)
* PR numbers (e.g., #789) …
=> Update script path

README.md
The repo URLs for cloning had `your-repo` instead of `The-AI-Alliance`. This PR fixes them.
N/A
N/A
Just a change to the `README.md`. 
N/A
=> Fixed typo in the GitHub URLs for the project.

.github/workflows/build-site.yml
Only attempt to build and launch the site on a merged PR
Related to #53
Doing it in the PR
=> Only Run Website Build and Deploy on Merged PR

.github/workflows/build-site.yml, website/_layouts/default.html
* What is the purpose of this PR?
* What new function or feature is being added?
* How does it improve the existing repository?
* Issue numbers (e.g., #123, #456)
* PR numbers (e.g., #789) …
=> Trying to get the build working

website/_includes/discord.html
Adds live button to 'Join Discord' Link
Closes #54 
Tested link in test build on local in my browser. 
Added link in two places- we should make an issue splitting out the navbar and 'join discord' button into their own `_includes`
=> Add live discord link

docs/index.md
I missed a bunch of `LLaMa` references when migrating this to The-AI-Alliance. 
Did another ctrl+r and found a bunch more instances of `llama models` and replaced them all with `large language models`.
Closes #1
N/A
Multiple files in docs.
=> replace llama models with large language models

.github/scripts/checks/general_review.py, .github/scripts/checks/schema_validation.py, .github/scripts/review_pr.py, .github/workflows/pr_review.yml
This PR Introduce LLM PR Reviews. 
The tests only run when the `run-tests` label is applied, we'll need to lock down the triage role.
Closes #42 
A reopening of #67 
Should open new issues for folding functionality into `gofannon` so that we're eating our own dog food.
Proof of Work: https://github.com/rawkintrevo/gofannon/pull/36
Adds files to `.github/scripts`
To use this the user must set repository secrets:
OPENAI_API_KEY
OPENAI_BASE_URL
OPENAI_MODEL_NAME
Note, that even though it says OpenAI, it means any OpenAI complient Endpoint (ie the example is running on Deepseek)
After merging make follow on issues for
1. Additional Tests
2. Incorporating this as a gofannon usecase/feature (including adding docs)
3. Issue for addressing specific …
=> Introduce LLM PR Reviews

gofannon/base/__init__.py, gofannon/base/langchain.py, gofannon/base/smol_agents.py
This PR refactors langchain and smolagents into seperate files and reintroduces them via mixin
Closes #43 
No changes to existing testing should be required. There were no breaking changes or new functionality added.
* New files or directories added: `gofannon/base/langchain.py` `gofannon/base/smolagents.py`
* Modified files or functions: `gofannon/base/__init__.py`
Usage has not changed.
=> Move smolagents and langchain to mixins

.gitignore, website/.gitignore, website/_includes/footer.html, website/_includes/head.html, website/_layouts/default.html, website/_layouts/docs.html, website/assets/css/style.css
PR Templates seem broken...
This adds header and footer to the website
=> Add Header and Footer

.gitignore, website/community/index.md
=> Add community page

ROADMAP.md
Update roadmap to include Documentation and Integration sections
=> Updated Roadmap.md

.github/PULL_REQUEST_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE/config.yml
It's a hack, but I think it will work.
=> Change to not allow blank PRs

.github/workflows/publish-to-pypi.yml
Workflow fails because poetry isn't installed
https://github.com/The-AI-Alliance/gofannon/actions/runs/13657833468/job/38181437962#step:7:14
Related to #73 
None
Added `Install Poetry` step
=> Install Poetry

docs/github/pr_review.md
* Added a link to how to deploy for more info
* docs/github/pr_review.md
=> Adding link to website docs for deploying pr review

website/about.md
Provide a brief description of the documentation or website changes:
* What content was added/modified/removed?
* Why were these changes made?
* How do these changes improve the documentation/website?
* Fixes #123
* Related to #456
=> Add comms channels

website/_config.yml, website/_includes/footer.html, website/community/index.md
Update the discord link
Closes #101 
Added link variable in _config.yml, updated files to pull from that.
=> Update discord link

README.md
Added build badges, mission statement, and usage example for better clarity, accessibility, and engagement. 
* What content was added/modified/removed?
* Why were these changes made?
* How do these changes improve the documentation/website?
* Closes #92 
* Added Build Badges for CI status, PyPI version, license, open issues, and GitHub stars.
* Included a Mission Statement outlining cross-framework compatibility, open-source education, and support for first-time contributors.
* Added a Communication Channels section listing Discord, GitHub Discussions, and Community Calls.
* Included a Usage Example to demonstrate basic functionality.
* Reformatted and enhanced structure for better readability.
* To improve project visibility and credibility with build …
=> [Docs/Website] Update the Readme

gofannon/base/__init__.py, gofannon/base/bedrock.py, gofannon/base/langchain.py, gofannon/base/smol_agents.py, pyproject.toml, scripts/build_lambda.sh, tests/integration/placeholder.txt, tests/integration/test_boto3.py, tests/unit/test_boto3.py
[Closes #35 - Integration with Bedrock Agents](https://github.com/The-AI-Alliance/gofannon/issues/35). Addition of Bedrock Agents backend implemented using AWS boto3.  
Allows the deployment of an existing function as a Bedrock Agent 
10 unit tests included in .`/tests/unit/test_boto3.py`. This is not 100% coverage, will re-visit when I get some more time.
1 integration test included in `./tests/integration/test_boto3.py.` This is a placeholder until a more complete integration suite can come online.
All unit tests in project executed and passed:
Addition of `./base/bedrock.py` in addition to aforementioned tests.
```
from gofannon.open_notify_space.iss_locator import IssLocator
agent_app_config = {
"app_id": "gofannon_demo",
"agent_name": "ISSLocator",
"agent_session_timeout": 600, …
```
=> Closes #35

website/about.md
The website/about.md file has been updated to include a new Community Leadership section under the existing Contributors heading. This section introduces the newly appointed co-leads of the project.
* Closes #109 
* website/about.md
- ✅ I have read the [CONTRIBUTING.md](CONTRIBUTING.md) guide
- ✅ My changes follow the documentation style guide
- ✅ I have updated any related documentation
=> Addition of community leadership

ROADMAP.md, docs/github/pr_review.md
=> Fixing emojis in ROADMAP

website/_config.yml
Click the `Preview` tab and select a PR template:
- [Docs/Website Only change](?expand=1&template=docs_website_pr.md)
- [Other change](?expand=1&template=general_code_pr.md)
[//]: # (Dumb that we have to do this hack, see https://github.com/orgs/community/discussions/4620 for progress on github fixing this)
=> updata ga tag

website/about.md
Provide a brief description of the documentation or website changes:
* Added a "Core Contributors" section under the "Community Leadership" section in website/about.md.
* Updated the "Community Leadership" heading to be more structured (## → ###).
* Included Joe Olson (@jolson-ibm) as a Core Contributor in recognition of his contributions.
* Minor text update: changed “See the list of …” to “See the full list of …” for clarity.
* Fixes #120 
- ✅ I have read the [CONTRIBUTING.md](CONTRIBUTING.md) guide
- ✅ My changes follow the documentation style guide
- ✅ I have updated any related documentation
=> Adding core contributors in website/about

README.md, website/about/index.md, website/about/the_name_gofannon.md
This PR moves the ```why_the_name_gofannon.md``` file from the docs/ directory to the website for better organization and accessibility.
* Fixes #119 
* Moved ```/why_the_name_gofannon.md``` → ```website/about/the_name_gofannon.md```
* Created a new ```website/about/``` 
* Renamed ```website/about.md``` → ```website/about/index.md``` to maintain existing links
* Updated ```website/about/index.md``` to include a link to the_name_gofannon(HTML)
* Updated README.md to reflect the new file location
- ✅ I have read the [CONTRIBUTING.md](CONTRIBUTING.md) guide
- ✅ My changes follow the documentation style guide
- ✅ I have updated any related documentation
=> [Docs/Website] Move "Why the Name Gofannon?" to Website

examples/smolagents+gofannon_quickstart.ipynb
=> add smolagents + gofannon example

website/about/index.md
This PR improves the formatting of the Core Contributors section by:
Combining multiple lists into a single table for better readability.
- Clearly differentiating Project Leads by:
- Bold text for project leads, with a note explaining it.
- Ensuring proper table headers and alignment using Kramdown markdown syntax.
* Fixes #136 
- ✅ Verified site builds successfully
- ✅ Checked links and formatting
- ✅ Tested in local development environment
- ✅ I have read the [CONTRIBUTING.md](CONTRIBUTING.md) guide
- ✅ My changes follow the documentation style guide
- ✅ I have updated any related documentation
=> Core contributors table formatting

.github/scripts/generate-roadmap.js
=> Fix Bug in roadmap gen

.github/ISSUE_TEMPLATE/agentic_framework.md
Add Framework Proposal
Closes #158
=> Framework Proposal Template

.github/workflows/publish-to-pypi.yml
Please provide a brief description of the changes made in this pull request:  
* This PR aims to address the feature request described in issue #169.  
* The new function or feature being added is the automated generation and publication of release notes as part of the weekly PyPI release workflow.  
* This improvement ensures that all changes included in a release are documented, enhancing transparency and simplifying change tracking for developers and users.  
List any related issues or PRs that this submission addresses:  
* Closes #169, which requested automation of release notes in the weekly PyPI release workflow.  
Describe the testing performed to validate the changes:  
None
Provide an overview of the code changes made:  
* Modified `.github/workflows/publish-to-pypi.yml` to …
=> Add Release Notes to Weekly Releases

docs/functions_and_tools_overview.md, website/_layouts/docs.html, website/how-tos/contribute_function.md, website/how-tos/contribute_tool.md, website/how-tos/index.md
Adds tutorial on how to contribute a tool for new users
Closes #166
=> [DOCS] How to conribute a Tool

gofannon/base/langchain.py
This request removes the warnings when importing tools from gofannon having to do with pydantic
#172 
https://github.com/The-AI-Alliance/proscenium/issues/33#issuecomment-2743309818
https://colab.research.google.com/drive/1GfVBmuaM06rVYjvXDXsg4M5a269-Zsu0?usp=sharing
Fix the import
=> [BUG} Pydantic Mess

gofannon/base/smol_agents.py, tests/unit/test_integrations.py
* What is the purpose of this PR?
* What new function or feature is being added?
* How does it improve the existing repository?
Closes #174  …
=> [wip] smolagents parameter bug

gofannon/github/commit_files.py
This PR fixes an issue in the `CommitFiles` tool where `git pull` fails due to missing tracking information for existing branches. The changes ensure reliable branch operations in automation scenarios by explicitly specifying remote branches during pull operations.  
* Fixes branch tracking issues in Git operations  
* Improves reliability of automated repository updates  
* Maintains backward compatibility with existing workflows  
* Closes #180 (Git pull tracking error in CommitFiles tool)  
* Manual testing with:  
- Existing branches (with and without tracking)  
- New branch creation  
- File commit/push operations  
* https://colab.research.google.com/drive/1KH809y9suBtgQfPGVsyh6s7Eqi1BUPv9?usp=sharing
* Modified `gofannon/github/commit_files.py`:  
- Changed `git pull` to …
=> [bug] Set git tracking in CommitFiles

.github/workflows/check_markdown_links.yml
Add markdown link check
Checks marked down file links to make sure they're alive does entire code base once a week does new files on full request
Closes #186 
Added `.github/workflows/check_markdown_links.yml`
=> Add markdown link checks

website/how-tos/index.md
Changed the relative url from contribute_function.html to contribute_tool.html
* Closes #182 
* /how-tos/index.md
=> Broken link fix to contribute tool

.github/scripts/generate_scoring_html.js, .github/workflows/build-site.yml, .github/workflows/leaderboard.yml, website/_includes/scoring.html, website/_layouts/leaderboard.html
Add scoring explanation to leaderboard see screenshots. Picks up changes from config Json automatically
Closes #202 
=> Add scoring explanation to leaderboard

website/how-tos/contribute_tool.md
Add first step to how to contribute a tool tutorial about creating issue and waiting for feedback
Closes #189 
Modified website/how-tos/contribute_tool.md
IntelliJ went ham adding spaces, sorry.
=> Add bit about creating issue first

website/how-tos/contribute_agentic_framework.md, website/how-tos/index.md
Provides documentation instructing how to contribute new framework
Closes #200 
=> Add documentation for contributing new agentic framework

.github/workflows/unit-tests.yml, gofannon/base/__init__.py, gofannon/base/langflow.py, pyproject.toml, tests/unit/test_integrations.py, tests/unit/test_langflow.py
Add langflow framework
Closes #185 
TODO: Deploy gofannon tool on langflow
New: `gofannon/base/langflow.py`, `tests/unit/test_langflow.py`
Modified: `pyproject.toml` 
Still need to add docs
=> [FRAMEWORK] Langflow

.github/release-drafter.yml, .github/workflows/publish-to-pypi.yml
Release notes were being populated as empty. This should fix by updating the config file and reordering the steps in the yaml
Related to #225 
Don't close issue until fix is confirmed. 
None- recon by fire. 
Re ordered steps in workflow-
update config file.
N/A
=> Fix Release Notes

CODE_OF_CONDUCT.md
Provide a brief description of the documentation or website changes:
Adds the AI Alliance Code of Conduct file.
* Fixes #194
* CODE_OF_CONDUCT.md
N/A
See #194 for discussion of options.
=> Add the Alliance CoC

docs/github/create_issue.md, gofannon/github/create_issue.py
Changes the way labels are passed from an array of strings (which smolagents has a hard time with) to a comma seperated list.
Fixes #257 
In a colab
Update gofannon/github/create_issue.py
=> labels for commit issue bugfix

docs/github/clone_repo.md, gofannon/github/clone_repo.py, tests/test_clone_repo.py
* Add Clone a github repository tool to a specific location
* Closes #263 
* Added test cases at `tests/test_clone_repo`
* Added new tool in the github tools file
* Added test cases to test the tool
```python
from gofannon.github.clone_repo import CloneRepo
tool = CloneRepo()
result = tool.fn(
repo_url="https://github.com/octocat/Hello-World.git",
local_dir="./cloned_repo"
)
print(result)
```
* Added a docstring to the class …
=> [Tool] github.CloneRepo

docs/file/read_file.md, gofannon/file/read_file.py, tests/test_read_file.py
* Add Read File Tool to read local files
* Closes #261 
* Added test cases at `tests/test_read_file`
* Added new folder for file
* Added Read File tool to the file folder
* Added test cases to the test folder
```python
from gofannon.file.read_file import ReadFile
tool = ReadFile()
result = tool.fn(
file_path="./data/input.txt"
)
print(result)
```
* None
=> [Tool] file.ReadFile

docs/github/list_issues.md, gofannon/github/list_issues.py, tests/test_list_issues.py
* Add List Issues Tool to list all issues in a GitHub Repository
* Closes #262 
* Added test cases at `tests/test_list_issues`
* Added List Issues to the GitHub tools folder
* Added test cases for the List Issues tool
```python
from gofannon.github.list_issues import ListIssues
tool = ListIssues(api_key="your_github_token")
result = tool.fn(
repo_url="https://github.com/The-AI-Alliance/gofannon",
state="open",
labels="bug,enhancement",
sort="updated",
direction="asc"
)
for issue in result:
print(issue["title"], issue["html_url"])
```
Confirm that the …
=> [Tool] github.ListIssues

website/community/index.md
Adds link to meetup-talk-in-a-box shared in google slides
Closes #277 
N/A
=> Add meetup-talk-in-a-box

tests/unit/llamastack/test_llamastack.py
* Added unit test for Llamastack framework
* Related to #161 
* Related to #275 
* Unit tests added 
* Added file for unit test cases
* Run test cases using `poetry run pytest tests/unit/llamastack/test_llamastack.py -v`
* None
=> [Unit Test] Llamastack Framework

.github/scripts/collect_metrics.py, .github/workflows/collect_metrics.yml
This PR introduces a script for doing an indepth metrics collection from github and a workflow for running that script and pushing the results to an S3 bucket
`None`
The script was tested with a colab - viewable [here](https://colab.research.google.com/drive/1-74mE2A4FxlzrTQ6qNpbRTZFMYpz4r7X?usp=sharing)
The workflow... yolo.
Script for collecting metrics
Workflow for running the script on cron and pushing result to s3
n/a
cc @planspark @dnielsen @deanwampler @adampingel @andrewmusselman @AnthonyJAnnunziata
=> Add automated Analytics collection

website/_includes/discord.html, website/about/index.md, website/community/index.md, website/developers/first_contribution.md
- Fixed Discord links to properly use the variable defined in `_config.yml`.
- Fixed broken links by appending missing `.html` to the URLs
Closes #286 
- website/_includes/discord.html
- website/about/index.md
- website/community/index.md
- website/developers/first_contribution.md
Built the site locally and verified that all updated links work correctly.
Although the `website/_includes/discord.html` file does not appear to be currently used, the Discord link inside it was updated for future use.
=> Fix invalid Discord links and broken internal link

.readthedocs.yaml
Add readthedocs
Related to #302
=> [infra] add readthedocs.yaml

README.md, gofannon/base/__init__.py, gofannon/base/adk_mixin.py, tests/unit/google/test_adk_mixin.py, website/index.md
Add Google ADK
Closes #307 
Added Unit Tests
Example in separate follow on PR
=> Add Google ADK

examples/Google_Search.ipynb, examples/Ollama_Example.ipynb, examples/smolagents+gofannon_quickstart.ipynb
Remove pydantic warnings from various notebooks
Closes #176
=> remove pydantic warnings

.github/workflows/build-site.yml, .github/workflows/check_markdown_links.yml, .github/workflows/collect_metrics.yml, .github/workflows/publish-to-pypi.yml, .github/workflows/stats-collector.yml
Closes #327 - GitHUb Actions Firing in Forked Repositories and Failing
The five jobs all now check if the job is running in the main repository. If not, skip.
Closes #327 - GitHUb Actions Firing in Forked Repositories and Failing
Verified all jobs exit without issue when run from my fork. Need to verify they execute properly in the main repository once merged.
Simple `if` statement inserted in the following actions:
`.github/workflows/build-site.yml`
`.github/workflows/check_markdown_links.yml`
`.github/workflows/collect_metrics.yml`
`.github/workflows/stats-collector.yml`
`.github/workflows/publish-to-pypi.yml`
=> Closes #327 - GitHUb Actions Firing in Forked Repositories and Failing

docs/github/index.md, docs/github/list_repo_files.md, docs/github/read_file.md, gofannon/github/list_repo_files.py, gofannon/github/read_file.py, manifest.json
Add list files to list files in a repo, add get file to get an individual file, updates manifiest with new tools and tools in grant_query.
None
=> no-jira: add list_repo_files and get file tools
